Check the tomcat service and restarting if required, While running ansible playbook we use "ansible-playbook my-playbook >> /home/opt/Ansible-tomcat-task.log" to
record all the logs. Next we will be configuring ELK on it so that it will be available all logs to the users through kibana UI and we are able to send
notification in form of RSS feeds for all the major events.

Hostfile
---------
[TOMCATSRVERS]
HOSTNAME1
HOSTNAME2
HOSTNAME3

- hosts: all
  # sudo permission
  become: true

  vars:
    tomcat_folder: qleoffice
    tomcat_path: "/home/testworkspace/{{ tomcat_folder }}"
    grep_string: "[/]home/testworkspace/{{ tomcat_folder }}"

  tasks:
    - name: ==> shutdown qle tomcat ,path = "{{ tomcat_path }}/bin/"
      command: sh {{ tomcat_path }}/bin/shutdown.sh

    - name: ==> sleep 3s
      command: sleep 3s

    - name: Check if Apache is running
      shell: ps aux | grep '{{ grep_string }}' | awk '{print $2}'
      ignore_errors: yes
      changed_when: false
      register: service_apache_status

    - debug: msg="Check if Apache is running {{ service_apache_status }}"
    - debug: msg="service_apache_status.stdout != '' =  {{ service_apache_status.stdout != ''}}"

    - name: kill process is tomcat is still running
      shell: kill $(ps aux | grep '{{ grep_string }}' | awk '{print $2}')
      when: service_apache_status.stdout != ''

    - command: sleep 1s
      when: service_apache_status.stdout != ''

    - name: ==> startup qle tomcat , path = {{ tomcat_path }}/bin/startup.sh
shell: setsid /bin/sh -i -c "{{ tomcat_path }}/bin/startup.sh"